apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortlist-app-ingress
  namespace: anusha-jammula
  annotations:
    # Keep this annotation for backward compatibility
    kubernetes.io/ingress.class: "nginx" 
spec:
  ingressClassName: nginx # 👈 Add this explicit line (or "alb" if using AWS Load Balancer Controller)
  rules:
  - host: radevsecops.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shortlist-app
            port:
              number: 80 
