name: Angular CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

    # Checkout Source Code
    - name: Checkout Source Code
      uses: actions/checkout@v4


    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22


    # Install Dependencies
    - name: Install Dependencies
      run: npm install


    # Skip Angular Tests
    - name: Skip Angular Tests
      run: echo "Skipping Angular Tests"


    # Build Angular Application
    - name: Build Angular Application
      run: npm run build -- --configuration=production


    # SonarQube Scan
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


    # Trivy File System Scan
    - name: Trivy File System Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .
        format: table
        exit-code: 0
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'


    # Zip Angular Build Artifact
    - name: Zip Angular Build Artifact
      run: |
       zip -r angular-build.zip dist/


# Upload Artifact to Nexus
    - name: Upload Artifact to Nexus
      run: |
        curl --fail -v \
        -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} \
        --upload-file angular-build.zip \
        ${{ secrets.NEXUS_REPO_URL }}/angular-build-${{ github.run_number }}.zip

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    # Login to Amazon ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2


    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t angular-app:${{ github.run_number }} .


    # Trivy Docker Image Scan
    - name: Trivy Docker Image Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'angular-app:${{ github.run_number }}'
        format: table
        exit-code: 0
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'


    # Tag Docker Image
    - name: Tag Docker Image
      run: |
        docker tag angular-app:${{ github.run_number }} \
        ${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}


    # Push Docker Image to ECR
    - name: Push Docker Image to ECR
      run: |
        docker push \
        ${{ secrets.ECR_REPOSITORY }}:${{ github.run_number }}

        # Deploy to ECS
    - name: Deploy to ECS
      run: |
        aws ecs update-service \
        --cluster angular-cluster \
        --service angular-service \
        --force-new-deployment \
        --region eu-west-2

    # Configure kubectl for EKS
    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig \
        --region eu-west-2 \
        --name angular-cluster


# Replace IMAGE_TAG
    - name: Update Kubernetes Deployment
      run: |
        sed -i "s|IMAGE_TAG|${{ github.run_number }}|g" k8s/deployment.yaml


# Deploy to EKS
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/




        
